import { Injectable } from '@nestjs/common';
import { SuperheroesService } from 'src/superheroes/superheroes.service';
import { CreateSuperheroDto } from 'src/superheroes/dto/create-superhero.dto';

@Injectable()
export class SeedService {
  constructor(private readonly superheroesService: SuperheroesService) {}

  async seed() {
    const heroes: CreateSuperheroDto[] = [
      {
        nickname: 'Avengers',
        real_name: 'Various',
        origin_description:
          'A group of Earth’s mightiest heroes assembled to fight threats no single hero can withstand.',
        superpowers: ['Teamwork', 'Strength', 'Leadership'],
        catch_phrase: 'Avengers, assemble!',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/a0/537ba3793915b/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/a/03/67e6c66206064/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/c0/67a67ef650bb6/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/60/679a4e5c64a02/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/f0/67ab71bba8997/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/40/67609411a9da2/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/f/80/679ba38edc4ab/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/b0/6760935703a92/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/03/67609236e407f/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/d0/673fa37b9e533/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/7/03/6780372ac8117/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/a/80/6764461228090/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/f/10/6750d4ca6dbcc/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/00/6750d4ca9eff7/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/e0/673370885341f/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/e0/66c7219e53e36/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/50/66c72139d3f11/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/10/66c7218289831/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/03/67112f79f3247/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/a/03/670683846cb31/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/40/66fc08a9b710b/portrait_uncanny.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/03/66d09933512b6/standard_incredible.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
        ],
      },
      {
        nickname: 'Iron Man',
        real_name: 'Tony Stark',
        origin_description:
          'Genius billionaire who created a powered armor suit to save his own life and become a hero.',
        superpowers: ['Genius intellect', 'Powered armor suit', 'Flight'],
        catch_phrase: 'I am Iron Man.',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/e0/661e9b6428e34/standard_incredible.jpg',
          'https://cdn.marvel.com/content/1x/default/comic-no-img.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/50/6826064f34403/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/50/6791566e7d7a4/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/70/67d9cefc6c9cf/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/30/67b74aab45d34/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/b0/6760935703a92/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/03/67609236e407f/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/50/678030cbf2f7b/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/b/03/67603a698361b/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/60/67603a8344155/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/2/03/6733705323ec2/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/70/67337040dcff5/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/60/67112f7a087e2/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/a/30/66e347deeb955/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/50/66a7f5a36ab2f/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/b/03/66634de912039/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/80/65d739964d4c7/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/90/66154192d7df1/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/00/65f0747aa8666/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/30/65ca4d4db8144/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/e0/4bb4eb40c8a7c/standard_incredible.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/b0/64c27983cb3c5/standard_incredible.png',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/d0/6513398a19581/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/c0/60e4af8657df1/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/b0/65148a885ba3f/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/10/64ef5763b9173/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/d0/65133a03a0113/standard_incredible.jpg',
        ],
      },
      {
        nickname: 'Captain America',
        real_name: 'Steve Rogers',
        origin_description:
          'A super-soldier from WWII revived in the modern day.',
        superpowers: ['Enhanced strength', 'Vibranium shield', 'Leadership'],
        catch_phrase: 'I can do this all day.',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/50/537ba56d31087/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/a0/68026dbd9c7ea/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/a/03/67e6c66206064/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/03/680146584cc21/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/c0/67ffe238de1f0/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/c0/67f5469699242/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/f0/67f5457fa091e/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/20/67ddb9be780e6/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/c0/67a67ef650bb6/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/d0/679a4e5c64442/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/60/679a4e5c64a02/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/60/67b74aab24e93/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/50/67b74ad8ae205/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/b0/678fd9014b722/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/e0/6781986c06986/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/1/60/6769722f380f7/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/40/67609411a9da2/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/30/6761cd5330c54/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/90/6761a61b707ff/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/03/67609236e407f/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/20/6761dca55b513/portrait_uncanny.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/80/67644a2f8e877/standard_incredible.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/03/654270074ae90/standard_incredible.jpg',
        ],
      },
      {
        nickname: 'Spider-Man',
        real_name: 'Peter Parker',
        origin_description: 'Teenager bitten by a radioactive spider.',
        superpowers: ['Wall-crawling', 'Spider-sense', 'Super strength'],
        catch_phrase: 'With great power comes great responsibility.',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/90/5a664c954a55b/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/30/6808f3d31abb6/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/e0/6809613a18927/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/7/c0/680f876698cce/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/f/03/67915677c11d5/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/40/67d3008bd753b/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/70/67b7a3390afb7/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/f0/67aa2a919ef68/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/5/d0/67a50b30b5f43/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/90/679a4f8b80d01/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/00/67b74ae5e68eb/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/7/10/67b74ae98a185/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/80/67b74af266996/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/10/678a9c7caf7e1/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/2/f0/67ab7161d1181/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/e0/67ab71b8483ff/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/a0/67ab71c7447c5/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/b0/67698b1445acb/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/00/679ba3a8b4ac0/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/a/40/67604ea89cc9f/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/2/f0/51252718e1c2d/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/80/65e5eab37f433/standard_incredible.png',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/b0/651487e458984/standard_incredible.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/7/10/6262e44859fdc/standard_incredible.png',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
        ],
      },
      {
        nickname: 'Deadpool',
        real_name: 'Wade Wilson',
        origin_description:
          'A mercenary with accelerated healing and a twisted sense of humor.',
        superpowers: ['Regeneration', 'Combat skills'],
        catch_phrase: 'Maximum effort!',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/5/c0/537ba730e05e0/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/d0/67c8ce75b61dc/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/8/a0/67ab7161da04a/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/d0/67ab717ce0e97/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/b/e0/67ab71c2cf0a6/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/2/b0/67ab71c704310/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/7/20/67ab71c775d69/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/60/679ba3e51cb63/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/70/67644610be4f3/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/90/676039c4db525/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/80/6750d4b7e8bda/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/c0/6750d4b35de86/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/f/30/6750d4cd3ccfb/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/7/50/67dc364a6f688/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/90/67337c7d11b84/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/80/67337c6c10e38/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/f0/66c721fdeeb69/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/2/b0/66a3eddfdc28f/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/c0/66a3ed6aa11dd/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/80/67068368c12ad/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/c0/66fc08aca3e89/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/90/65148c4b6bd38/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/10/63863e4987032/standard_incredible.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
        ],
      },
      {
        nickname: 'Black Panther',
        real_name: 'T’Challa',
        origin_description:
          'King of Wakanda with enhanced abilities and access to advanced technology.',
        superpowers: ['Enhanced strength', 'Vibranium suit', 'Leadership'],
        catch_phrase: 'Wakanda Forever!',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/1/c0/537ba2bfd6bab/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/a0/68026dbd9c7ea/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/03/680146584cc21/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/c0/67ffe238de1f0/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/c0/67f5469699242/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/f0/67f5457fa091e/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/20/67ddb9be780e6/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/a/50/6780374233135/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/03/67644610af523/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/30/6750d4c18340e/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/f/03/6733708063e9e/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/b0/67337079b61af/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/3/e0/66c7219e53e36/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/7/00/66a3ee987118c/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/10/6706838038b49/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/9/90/66e347bce52f2/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/8/70/66bb70e014ba2/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/1/30/66bb716729729/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/60/6679754b99c1a/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/00/66634e1798ca4/portrait_uncanny.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/d0/664b9def1c84b/portrait_uncanny.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/e/10/63863e4987032/standard_incredible.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/content/1x/default/series-no-img.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/f0/64873d2b59be5/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/d/d0/6513398a19581/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/a0/5e4c14fe991ad/standard_incredible.jpg',
          'https://cdn.marvel.com/u/prod/marvel/i/mg/4/40/6514877f6f6b3/standard_incredible.jpg',
        ],
      },
      {
        nickname: 'Jessica Jones',
        real_name: 'Jessica Jones',
        origin_description:
          'Private investigator with super strength and trauma from past events.',
        superpowers: ['Super strength', 'Investigation'],
        catch_phrase: 'Alias Investigations.',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/b0/662c2568c6e0f/standard_incredible.jpg',
        ],
      },
      {
        nickname: 'Ant-Man',
        real_name: 'Scott Lang',
        origin_description:
          'A thief turned superhero with a suit that can change size.',
        superpowers: ['Size manipulation', 'Ant communication'],
        catch_phrase: 'I do some dumb things.',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/6/90/54ad7297b0a59/standard_incredible.jpg',
        ],
      },
      {
        nickname: 'Captain Marvel',
        real_name: 'Carol Danvers',
        origin_description:
          'Air Force pilot transformed into one of the universe’s most powerful heroes.',
        superpowers: ['Energy projection', 'Flight', 'Super strength'],
        catch_phrase: 'Higher, further, faster.',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_incredible.jpg',
        ],
      },
      {
        nickname: 'Guardians of the Galaxy',
        real_name: 'Various',
        origin_description: 'A ragtag group of misfits defending the galaxy.',
        superpowers: ['Varied among members'],
        catch_phrase: 'We are Groot.',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/c/10/537babe1c1f66/standard_incredible.jpg',
        ],
      },
      {
        nickname: 'Wolverine',
        real_name: 'Logan',
        origin_description:
          'A mutant with healing powers and adamantium claws.',
        superpowers: ['Regeneration', 'Claws', 'Enhanced senses'],
        catch_phrase: 'I’m the best there is at what I do.',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/2/60/537bcaef0f6cf/standard_incredible.jpg',
        ],
      },
      {
        nickname: 'Luke Cage',
        real_name: 'Luke Cage',
        origin_description:
          'Experimented on in prison, gained super strength and unbreakable skin.',
        superpowers: ['Super strength', 'Durability'],
        catch_phrase: 'Sweet Christmas!',
        images: [
          'https://cdn.marvel.com/u/prod/marvel/i/mg/5/e0/537bb460046bd/standard_incredible.jpg',
        ],
      },
    ];

    for (const hero of heroes) {
      await this.superheroesService.create(hero);
    }
  }
}
